"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StylesDesignModule = void 0;
require("./ko/bindingHandlers/bindingHandlers.colorPicker");
require("./ko/bindingHandlers/bindingHandlers.jss");
require("./ko/bindingHandlers/bindingHandlers.shadowPreview");
require("./ko/bindingHandlers/bindingHandlers.gradientPreview");
require("./ko/bindingHandlers/bindingHandlers.itemTemplate");
require("./ko/bindingHandlers/bindingHandlers.fontGlyph");
var styleEditor_1 = require("./workshops/styleEditor");
var styleGuide_1 = require("./styleGuide/styleGuide");
var boxEditor_1 = require("./workshops/boxes/boxEditor");
var border_1 = require("./workshops/border");
var colors_1 = require("./workshops/colors");
var gradients_1 = require("./workshops/gradients");
var fonts_1 = require("./workshops/fonts");
var googleFonts_1 = require("./workshops/googleFonts");
var animations_1 = require("./workshops/animations");
var animationEditor_1 = require("./workshops/animations/animationEditor");
var shadows_1 = require("./workshops/shadows");
var typography_1 = require("./workshops/typography");
var background_1 = require("./workshops/background");
var bindingHandlers_styleSheet_1 = require("./ko/bindingHandlers/bindingHandlers.styleSheet");
var plugins_1 = require("./plugins");
var stylesSection_1 = require("./workshops/stylesSection");
var bindingHandlers_stylePreview_1 = require("./ko/bindingHandlers/bindingHandlers.stylePreview");
var bindingHandlers_styleable_1 = require("./ko/bindingHandlers/bindingHandlers.styleable");
var transform_1 = require("./workshops/transform/transform");
var transition_1 = require("./workshops/transitions/transition");
var container_1 = require("./workshops/container/container");
var styleSnippetSelector_1 = require("./workshops/snippets/styleSnippetSelector");
var styleSnippetService_1 = require("./styleSnippetService");
var styleSnippet_1 = require("./workshops/snippets/styleSnippet");
var styleVariationSelector_1 = require("./workshops/snippets/styleVariationSelector");
var bindingHandlers_1 = require("./ko/bindingHandlers");
var optionSelectorEditor_1 = require("./workshops/optionSelector/optionSelectorEditor");
var sizeEditor_1 = require("./workshops/size/sizeEditor");
var glyph_selector_1 = require("./workshops/icons/glyph-selector/glyph-selector");
var glyph_import_1 = require("./workshops/icons/glyph-import/glyph-import");
var glyph_input_1 = require("./workshops/icons/glyph-input/glyph-input");
var fontPermalinkResolver_design_1 = require("./fonts/fontPermalinkResolver.design");
var styleService_1 = require("./styleService");
var defaultStyleCompiler_1 = require("./defaultStyleCompiler");
var openType_1 = require("./openType");
var fontEditor_1 = require("./workshops/fonts/fontEditor");
var StylesDesignModule = (function () {
    function StylesDesignModule() {
    }
    StylesDesignModule.prototype.register = function (injector) {
        injector.bind("fontSelector", fonts_1.FontSelector);
        injector.bind("glyphSelector", glyph_selector_1.GlyphSelector);
        injector.bind("glyphImport", glyph_import_1.GlyphImport);
        injector.bind("glyphInput", glyph_input_1.GlyphInput);
        injector.bind("googleFonts", googleFonts_1.GoogleFonts);
        injector.bind("typography", typography_1.Typography);
        injector.bind("container", container_1.Container);
        injector.bind("background", background_1.Background);
        injector.bind("transform", transform_1.Transform);
        injector.bind("transition", transition_1.Transition);
        injector.bind("boxEditor", boxEditor_1.BoxEditor);
        injector.bind("sizeEditor", sizeEditor_1.SizeEditor);
        injector.bind("borderEditor", border_1.BorderEditor);
        injector.bind("optionSelectorEditor", optionSelectorEditor_1.OptionSelectorEditor);
        injector.bind("colorSelector", colors_1.ColorSelector);
        injector.bind("colorEditor", colors_1.ColorEditor);
        injector.bind("colorPickerView", gradients_1.ColorStopEditor);
        injector.bind("gradientSelector", gradients_1.GradientSelector);
        injector.bind("gradientEditor", gradients_1.GradientEditor);
        injector.bind("shadowSelector", shadows_1.ShadowSelector);
        injector.bind("shadowEditor", shadows_1.ShadowEditor);
        injector.bind("shadowEditorGroup", shadows_1.ShadowEditorGroup);
        injector.bind("animationSelector", animations_1.AnimationSelector);
        injector.bind("animationEditor", animationEditor_1.AnimationEditor);
        injector.bindSingleton("styleService", styleService_1.StyleService);
        injector.bindSingleton("styleCompiler", defaultStyleCompiler_1.DefaultStyleCompiler);
        injector.bindToCollection("autostart", bindingHandlers_1.StyledBindingHandler);
        injector.bind("fontEditor", fontEditor_1.FontEditor);
        injector.bindSingleton("fontManager", openType_1.FontManager);
        injector.bind("styleEditor", styleEditor_1.StyleEditor);
        injector.bind("styleGuide", styleGuide_1.StyleGuide);
        injector.bind("stylePlugin", plugins_1.StylePlugin);
        injector.bind("styleSnippet", styleSnippet_1.StyleSnippet);
        injector.bind("styleSnippetSelector", styleSnippetSelector_1.StyleSnippetSelector);
        injector.bind("styleVariationSelector", styleVariationSelector_1.StyleVariationSelector);
        injector.bindSingleton("styleSnippetService", styleSnippetService_1.StyleSnippetService);
        injector.bindToCollection("autostart", bindingHandlers_styleSheet_1.StylesheetBindingHandler);
        injector.bindToCollection("autostart", bindingHandlers_stylePreview_1.StylePreviewBindingHandler);
        injector.bindToCollection("autostart", bindingHandlers_styleable_1.StylableBindingHandler);
        injector.bindToCollection("workshopSections", stylesSection_1.StylesWorkshopSection);
        injector.bindToCollection("autostart", bindingHandlers_1.StyledBindingHandler);
        injector.bindToCollection("permalinkResolvers", fontPermalinkResolver_design_1.FontPermalinkResolver, "fontPermalinkResolver");
    };
    return StylesDesignModule;
}());
exports.StylesDesignModule = StylesDesignModule;
