version: 2.1

workflows:
  frontend-workflow:
    jobs:
      - release-packages:
          context:
            - reaction-publish-semantic-release

jobs:
  release-packages:
    docker:
      - image: node:12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: example12


    working_directory: ~/repo

    steps:
      - run: echo $NPM_TOKEN && echo $GITHUB_TOKEN
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # run tests!

      - run: git config --global github.token $GITHUB_TOKEN
      - run: git config --global user.email wittycodes@gmail.com
      - run: git config --global user.name pgarg
      - run: npm install
      - run: yarn new-version

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: git tag
      - run: echo 'export TAG=`git describe --abbrev=0 --tags $(git rev-list --tags --max-count=2) | sed -n 2p`' >> $BASH_ENV
      - run: echo $TAG
      - run: yarn ci:deploy
