"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CoreModule = void 0;
const blocks_1 = require("@paperbits/common/blocks");
const blogs_1 = require("@paperbits/common/blogs");
const configuration_1 = require("@paperbits/common/configuration");
const events_1 = require("@paperbits/common/events");
const http_1 = require("@paperbits/common/http");
const layoutService_1 = require("@paperbits/common/layouts/layoutService");
const localization_1 = require("@paperbits/common/localization");
const media_1 = require("@paperbits/common/media");
const persistence_1 = require("@paperbits/common/persistence");
const navigation_1 = require("@paperbits/common/navigation");
const pages_1 = require("@paperbits/common/pages");
const pagePermalinkResolver_1 = require("@paperbits/common/pages/pagePermalinkResolver");
const permalinks_1 = require("@paperbits/common/permalinks");
const routing_1 = require("@paperbits/common/routing");
const sites_1 = require("@paperbits/common/sites");
const urls_1 = require("@paperbits/common/urls");
const urlPermalinkResolver_1 = require("@paperbits/common/urls/urlPermalinkResolver");
const widgets_1 = require("@paperbits/common/widgets");
const background_1 = require("@paperbits/common/widgets/background");
const button_module_1 = require("./button/ko/button.module");
const card_module_1 = require("./card/ko/card.module");
const ko_1 = require("./collapsible-panel/ko");
const column_module_1 = require("./column/ko/column.module");
const ko_2 = require("./content/ko");
const gridCell_module_1 = require("./grid-cell/ko/gridCell.module");
const grid_module_1 = require("./grid-layout-section/ko/grid.module");
const bindingHandlers_background_1 = require("./ko/bindingHandlers/bindingHandlers.background");
const bindingHandlers_secured_1 = require("./ko/bindingHandlers/bindingHandlers.secured");
const bindingHandlers_widget_1 = require("./ko/bindingHandlers/bindingHandlers.widget");
const knockout_loaders_1 = require("./ko/knockout.loaders");
const ko_module_1 = require("./ko/ko.module");
const viewModelBinderSelector_1 = require("./ko/viewModelBinderSelector");
const ko_3 = require("./menu/ko");
const navbar_module_1 = require("./navbar/ko/navbar.module");
const picture_module_1 = require("./picture/picture.module");
const row_module_1 = require("./row/ko/row.module");
const section_module_1 = require("./section/ko/section.module");
const testimonials_module_1 = require("./testimonials/ko/testimonials.module");
const textblock_module_1 = require("./textblock/ko/textblock.module");
const videoPlayer_publish_module_1 = require("./video-player/videoPlayer.publish.module");
const youtubePlayer_publish_module_1 = require("./youtube-player/youtubePlayer.publish.module");
class CoreModule {
    register(injector) {
        injector.bindCollection("autostart");
        injector.bindCollection("styleHandlers");
        injector.bindCollectionLazily("widgetHandlers");
        injector.bindCollectionLazily("routeGuards");
        injector.bindCollectionLazily("modelBinders");
        injector.bindCollectionLazily("viewModelBinders");
        injector.bindCollectionLazily("permalinkResolvers");
        injector.bindSingleton("settingsProvider", configuration_1.DefaultSettingsProvider);
        injector.bindSingleton("router", routing_1.DefaultRouter);
        injector.bindSingleton("httpClient", http_1.XmlHttpRequestClient);
        injector.bindSingleton("eventManager", events_1.DefaultEventManager);
        injector.bindSingleton("globalEventHandler", events_1.GlobalEventHandler);
        injector.bindSingleton("changeCommitter", persistence_1.DefaultChangeCommitter);
        injector.bindSingleton("widgetService", widgets_1.WidgetService);
        injector.bindSingleton("permalinkService", permalinks_1.DefaultPermalinkService);
        injector.bindSingleton("layoutService", layoutService_1.LayoutService);
        injector.bindSingleton("pageService", pages_1.PageService);
        injector.bindSingleton("blogService", blogs_1.BlogService);
        injector.bindSingleton("mediaService", media_1.MediaService);
        injector.bindSingleton("blockService", blocks_1.BlockService);
        injector.bindSingleton("navigationService", navigation_1.NavigationService);
        injector.bindSingleton("siteService", sites_1.SiteService);
        injector.bindSingleton("urlService", urls_1.UrlService);
        injector.bindSingleton("localeService", localization_1.LocaleService);
        injector.bindSingleton("permalinkResolver", permalinks_1.PermalinkResolver);
        injector.bindToCollection("permalinkResolvers", pagePermalinkResolver_1.PagePermalinkResolver, "pagePermalinkResolver");
        injector.bindToCollection("permalinkResolvers", urlPermalinkResolver_1.UrlPermalinkResolver, "urlPermalinkResolver");
        injector.bind("modelBinderSelector", widgets_1.ModelBinderSelector);
        injector.bind("viewModelBinderSelector", viewModelBinderSelector_1.ViewModelBinderSelector);
        injector.bind("backgroundModelBinder", background_1.BackgroundModelBinder);
        injector.bindModule(new knockout_loaders_1.KnockoutRegistrationLoaders());
        injector.bindModule(new ko_module_1.KoModule());
        injector.bindModule(new ko_2.ContentModule());
        injector.bindModule(new column_module_1.ColumnModule());
        injector.bindModule(new row_module_1.RowModule());
        injector.bindModule(new textblock_module_1.TextblockModule());
        injector.bindModule(new section_module_1.SectionModule());
        injector.bindModule(new grid_module_1.GridModule());
        injector.bindModule(new gridCell_module_1.GridCellModule());
        injector.bindModule(new navbar_module_1.NavbarModule());
        injector.bindModule(new button_module_1.ButtonModule());
        injector.bindModule(new ko_3.MenuModule());
        injector.bindModule(new picture_module_1.PictureModule());
        injector.bindModule(new videoPlayer_publish_module_1.VideoPlayerModule());
        injector.bindModule(new youtubePlayer_publish_module_1.YoutubePlayerPublishModule());
        injector.bindModule(new testimonials_module_1.TestimonialsModule());
        injector.bindModule(new card_module_1.CardModule());
        injector.bindModule(new ko_1.CollapsiblePanelModule());
        injector.bindToCollection("routeGuards", routing_1.DefaultRouteGuard);
        injector.bindToCollection("autostart", bindingHandlers_widget_1.WidgetBindingHandler);
        injector.bindToCollection("autostart", bindingHandlers_background_1.BackgroundBindingHandler);
        injector.bindToCollection("autostart", bindingHandlers_secured_1.SecuredBindingHandler);
    }
}
exports.CoreModule = CoreModule;
//# sourceMappingURL=core.module.js.map