apiVersion: skaffold/v2beta8
kind: Config
build:
  local:
    push: true
    useDockerCLI: true

  tagPolicy:
    gitCommit: {}

  artifacts:

    - image: craflo-web
      context: ./
      docker:
        buildArgs:
          DEBUG: 1
      sync:
        manual:
          # Sync all the javascript files that are in the src folder
          # with the container src folder
          - src: '**/*'
            dest: '/usr/local/src/app/'




deploy:
  statusCheckDeadlineSeconds: 300
  helm:    # beta uses the helm CLI to apply the charts to the cluster.
    releases:    # a list of Helm releases.
      - name: 'craflo'
        version: 0.1.0
        chartPath: './craflo-commerce-charts'
        valuesFiles: ['./craflo-commerce-charts/values.yaml']
        namespace: craflo-system
        skipBuildDependencies: false
        artifactOverrides:

          web:
            image:
              repository: craflo-web
#              tag: dev



#  kubectl:
#    manifests:
#      - ../craflo-infra-charts/namespace.yaml