{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "reactioncommerce.fullname" . }}-web
  labels:
    app: {{ template "reactioncommerce.name" . }}
    component: web
    chart: {{ template "reactioncommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- if .Values.web.service.annotations }}
{{ toYaml .Values.web.service.annotations | trim | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app: {{ template "reactioncommerce.name" . }}
    component: web
    release: {{ .Release.Name }}
  ports:
    - name: "web"
      port: 8080
      targetPort: 8080
{{- end }}
