# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost
  web:
    external:
      name: web

services:
  fe-shop-admin:
    image: reactioncommerce/admin:3.0.0-beta.9
    env_file:
      - ./.env
    networks:
      default:
      reaction:
      web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fe-shop-admin.entrypoints=http"
      - "traefik.http.routers.fe-shop-admin.rule=Host(`make.craflo.com`)"
      - "traefik.http.middlewares.fe-shop-admin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.fe-shop-admin.middlewares=fe-shop-admin-https-redirect"
      - "traefik.http.routers.fe-shop-admin-secure.entrypoints=https"
      - "traefik.http.routers.fe-shop-admin-secure.rule=Host(`make.craflo.com`)"
      - "traefik.http.routers.fe-shop-admin-secure.tls=true"
      - "traefik.http.routers.fe-shop-admin-secure.service=fe-shop-admin"
      - "traefik.http.services.fe-shop-admin.loadbalancer.server.port=4080"
      - "traefik.docker.network=web"
