name: Publish Packages
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

#      - name: cache-yarn-cache
#        uses: actions/cache@v2
#        with:
#          path: |
#            node_modules
#            */*/node_modules
#          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: yarn global add lerna

#      - run: yarn bootstrap
#        if: steps.cache-yarn-cache.outputs.cache-hit != 'true'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

#      - name: cache-yarn-cache
#        uses: actions/cache@v2
#        with:
#          path: |
#            node_modules
#            */*/node_modules
#          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: yarn global add lerna

#      - run: yarn bootstrap
#        if: steps.cache-yarn-cache.outputs.cache-hit != 'true'

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@craflo"

      - run: git stash && yarn publish-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@paperbits"

      - run: git stash && yarn publish-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
