"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./polyfills");
const ko = require("knockout");
const injection_1 = require("@paperbits/common/injection");
const core_design_module_1 = require("@paperbits/core/core.design.module");
const forms_design_module_1 = require("@paperbits/forms/forms.design.module");
const emails_design_module_1 = require("@paperbits/emails/emails.design.module");
const styles_design_module_1 = require("@paperbits/styles/styles.design.module");
const prosemirror_module_1 = require("@paperbits/prosemirror/prosemirror.module");
const offline_module_1 = require("@paperbits/common/persistence/offline.module");
const demo_design_module_1 = require("./modules/demo.design.module");
const injector = new injection_1.InversifyInjector();
injector.bindModule(new core_design_module_1.CoreDesignModule());
injector.bindModule(new forms_design_module_1.FormsDesignModule());
injector.bindModule(new emails_design_module_1.EmailsDesignModule());
injector.bindModule(new styles_design_module_1.StylesDesignModule());
injector.bindModule(new prosemirror_module_1.ProseMirrorModule());
injector.bindModule(new demo_design_module_1.DemoDesignModule());
injector.bindModule(new offline_module_1.OfflineModule({ autosave: false }));
injector.resolve("autostart");
document.addEventListener("DOMContentLoaded", () => {
    setImmediate(() => ko.applyBindings(undefined, document.body));
});
